name: v7-ci
on:
  push: { branches: [ main, feat/**, chore/**, refactor/** ] }
  pull_request: { branches: [ main ] }

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Validate
        run: make validate
      - name: Upload validation artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: validation-artifacts
          path: |
            validation/metrics_summary.json
            validation/VALIDATION.md
